### ISSUE TITLE
Needing a little help running the code

### ISSUE THREAD

**Issue by afonsocarmo** [briangordon/CelesteExtractor#2]
I don't know how to code but I really want to have access to these images. Is there any way you could instruct me more in more detail about what I have to do?

**Comment by briangordon** [comment]
What platform are you on? The commands in the readme should work if you're on MacOS. On Linux or Windows (in a WSL bash shell) it should be the same, just with a different path to Steam.

**Comment by hojony** [comment]
> What platform are you on? The commands in the readme should work if you're on MacOS. On Linux or Windows (in a WSL bash shell) it should be the same, just with a different path to Steam.

Same question.  No idea about coding.  Need more instructions. Thanks.

**Comment by briangordon** [comment]
As I said, the readme provides the exact commands you'll need to run in the terminal if you're on MacOS. It's a command line application with no graphical UI so unfortunately there's no getting around the need for a basic familiarity with the command line. If you're on Windows you can [install Windows Subsystem for Linux](https://docs.microsoft.com/en-us/learn/modules/get-started-with-windows-subsystem-for-linux/) to get a command line, or try to use PowerShell. You may also have an easier time with [this fork](https://github.com/dragongling/CelesteExtractor/tree/master/CelesteExtractorNF) of CelesteExtractor which looks a bit easier to use.

**Comment by Voidrius** [comment]
Yeah the code probably works but how exactly do I run the code with dotnet on windows?

**Comment by briangordon** [comment]
> Yeah the code probably works but how exactly do I run the code with dotnet on windows?

All right, I'll write a detailed tutorial for Windows users, probably later today.

**Comment by TeWu** [comment]
@Voidrius @hojony @afonsocarmo If you have issues running this extractor program, you can try your luck with the one I've just made in Java: **[TeWu/CelesteExtractor](https://github.com/TeWu/CelesteExtractor)**. Alternatively there is also **[wtdcode/CelesteExtractor](https://github.com/wtdcode/CelesteExtractor)** written in C#. Hope this helps 😃

**Comment by briangordon** [comment]
Thanks @TeWu - it looks like this is the simple point-and-click solution that people have been requesting! 

I apologize for this slipping my mind last week. I don't think there's a need anymore for me to add more explanatory steps to the readme like I had planned. If it's okay with you, I'm just going to update the readme to include a suggestion that users looking for an easy point-and-click conversion should check out your project instead. Assuming you have no objections I'll likely get to it tomorrow.

**Comment by TeWu** [comment]
Oh sure! I'm perfectly okay with it, so by all means go ahead. 👍
I would also appreciate if You could verify, that my extractor program is working properly on your system.

**Comment by briangordon** [comment]
I've added a PowerShell example for Windows users and linked to TeWu's project. Closing this issue.
