### ISSUE TITLE
Filename Too Long

### ISSUE THREAD

**Issue by Heptor44** [briangordon/CelesteExtractor#3]
When I try to use this with PowerShell, it throws this:
![image](https://user-images.githubusercontent.com/59123926/102427015-169ef700-3fd6-11eb-859b-125cea4f409d.png)

**Comment by briangordon** [comment]
Oh dear. You caught my lack of testing. I added some notes in the readme about the problem you're running into. I'm sorry the situation is so gross on windows 😦 

If someone wants to fork this and give it a frontend that just accepts the Celeste install directory and converts _everything_ then I'll gladly link to it in the readme.
